[package]
publish = false
name = "metamatch_debug"
edition = "2021"

[dependencies]
proc-macro2 = "1.0.94"
syn = "2.0.100"
prettyplease = "0.2.31"
clap = { version = "4.5.32", features = ["derive"] }

[features]
default = ["debug"]
debug = []
